wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1660634951.734114
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.13
      5: 0.13.1
      8:
      - 1
      - 5
